version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postes
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always

    ports:
      - "8080:8080"
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:root@postgres:5432/postes
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
